{% set name = "pem" %}
{% set version = "23.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pem-{{ version }}.tar.gz
  sha256: 06503ff2441a111f853ce4e8b9eb9d5fedb488ebdbf560115d3dd53a1b4afc73

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pem
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: PEM file parsing in Python.
  license: MIT
  license_file: LICENSE
  home: https://github.com/hynek/pem

extra:
  recipe-maintainers:
    - millsks
